# Generated by Django 6.0.7 on 2026-07-08 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cookie_id', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='posts.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['post'], name='analytics_p_post_id_9538f0_idx'), models.Index(fields=['user'], name='analytics_p_user_id_e3b3b6_idx'), models.Index(fields=['ip_address'], name='analytics_p_ip_addr_7111ed_idx'), models.Index(fields=['cookie_id'], name='analytics_p_cookie__8f8107_idx'), models.Index(fields=['viewed_at'], name='analytics_p_viewed__2f3c45_idx')],
            },
        ),
    ]
