# Generated by Django 6.0.7 on 2026-07-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
    ]
