"""
Django settings for community project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import logging
from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "allauth": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "django": {
            "handlers": ["console"],
            "level": "ERROR",
        },
    },
}
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    '192.168.11.18',
    'heaven',
    "192.168.11.15",
    "localhost",
    "127.0.0.1",
    "192.168.11.20",
    "tokeisanheaven.ddns.net",
    ".onrender.com",
]

SOCIALACCOUNT_LOGIN_ON_GET = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'posts',
    'comments',
    'accounts',
    'likes',
    'analytics',
    'tags',
    'events',
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "storages",
    "django.contrib.sites",

    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.discord",
    "allauth.socialaccount.providers.twitter_oauth2",
]

SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-development-only"
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

SOCIALACCOUNT_PROVIDERS = {
    "discord": {
        "APPS": [
            {
                "client_id": os.environ.get("DISCORD_CLIENT_ID"),
                "secret": os.environ.get("DISCORD_CLIENT_SECRET"),
                "key": "",
            }
        ]
    },
    "github": {
        "APPS": [
            {
                "client_id": os.environ.get("GITHUB_CLIENT_ID"),
                "secret": os.environ.get("GITHUB_CLIENT_SECRET"),
                "key": "",
            }
        ]
    },
    "google": {
        "APPS": [
            {
                "client_id": os.environ.get("GOOGLE_CLIENT_ID"),
                "secret": os.environ.get("GOOGLE_CLIENT_SECRET"),
                "key": "",
            }
        ]
    },
    "twitter_oauth2": {
        "APPS": [
            {
                "client_id": os.environ.get("TWITTER_CLIENT_ID"),
                "secret": os.environ.get("TWITTER_CLIENT_SECRET"),
                "key": "",
            }
        ]
    },
}


ROOT_URLCONF = 'community.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "analytics.context_processors.sidebar",
            ],
        },
    },
]

WSGI_APPLICATION = 'community.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'community',
#        'USER': 'hori',
#        'PASSWORD': os.environ["DB_PASSWORD"],
#        'HOST': 'localhost',
#        'PORT': '5432',
#    }
#}


import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///db.sqlite3"
    )
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
CSRF_TRUSTED_ORIGINS = [
    "https://192.168.11.18",
    "https://192.168.11.20",
    "https://tokeisanheaven.ddns.net/",
]

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

#MEDIA_ROOT = "/data/media"


STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": os.environ.get("SUPABASE_ACCESS_KEY_ID"),
            "secret_key": os.environ.get("SUPABASE_SECRET_ACCESS_KEY"),
            "bucket_name": os.environ.get("SUPABASE_STORAGE_BUCKET"),
            "endpoint_url": os.environ.get("SUPABASE_S3_ENDPOINT_URL"),
            "region_name": os.environ.get("SUPABASE_REGION", "ap-northeast-1"),
            "addressing_style": "path",
            "querystring_auth": False,
            "file_overwrite": False,
            "custom_domain": "https://mbaidjvectlshqqbrfjp.storage.supabase.co/storage/v1/object/public/media",
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

#STATIC_URL = "/static/"
#STATIC_ROOT = "/data/static"

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'



